blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'

urlpatterns = [

	#list of posts
	url(r'^$', views.post_list, name ='post_list'),

	#details of post + comments
	url(r'^post/(?P<pk>\d+)/$', views.post_detail, name ='post_detail'),

	#adding post
	url(r'^post/new/$', views.post_add, name='post_add'),

	#publishing post
	url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),

	#draft posts
	url(r'^draft_posts$', views.post_drafts, name='post_drafts'),

	#editing post
	url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),

	#removing post
	url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),

	#removing comment
	url(r'^post/(?P<pk>\d+)/comment_remove/$', views.comment_remove, name='comment_remove'),

]

contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns = [
	url(r'^$', views.contact , name = "contact" ),
	url(r'^messages/$', views.message_list , name = "message_list" ),
	url(r'^messages/(?P<pk>\d+)/$', views.message_detail , name = "message_detail" ),
	url(r'^messages/delete/(?P<pk>\d+)/$', views.message_delete , name = "message_delete" ),
]

cvsite/urls.py
from django.conf.urls import include, url 
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^accounts/login/$', login, {'template_name': 'main/admin/login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
]

portfolio/urls.py
from django.conf.urls import url 
from . import views

app_name = 'portfolio'

urlpatterns = [
    url(r'^$', views.portfolio_list, name='portfolio_list'),
    url(r'^details/(?P<pk>\d+)/$', views.portfolio_details, name='portfolio_details'),
    url(r'^web/$', views.portfolio_web, name='portfolio_web'),
    url(r'^program/$', views.portfolio_programs, name='portfolio_programs'),
    url(r'^bots/$', views.portfolio_bots, name='portfolio_bots'),
    url(r'^mobile_apps/$', views.portfolio_mobile_apps, name='portfolio_mobile_apps'),
    url(r'^add_project/$', views.portfolio_add_project, name='portfolio_add_project'),
    url(r'^delete/(?P<pk>\d+)/$', views.portfolio_delete_project, name='portfolio_delete_project'),
    url(r'^edit/(?P<pk>\d+)/$', views.portfolio_edit_project, name='portfolio_edit_project')
]

portfolio/models.py
from django.db import models
from django.utils import timezone


class Portfolio(models.Model):

	# CATEGORY CHOICES

	web = 'Web'
	program = 'Program'
	bots = 'Bots'
	mobile_app = 'Mobile App'
	category_choices = (
		(web, 'Web'),
		(program, 'Program'),
		(bots, 'Bots'),
		(mobile_app, 'Mobile App'),
		)

	# ---------------------------

	name = models.CharField(max_length=200)
	creator = models.CharField(max_length=100)
	category = models.CharField(max_length=10, choices=category_choices)
	description = models.TextField()
	technologies = models.CharField(max_length=300, default=None)
	screen_link = models.CharField(max_length=500)
	source_code_link = models.CharField(max_length=300, blank=True, null=True)
	project_link = models.CharField(max_length=300, blank=True, null=True)
	date = models.DateTimeField(default=timezone.now)


	def __str__(self):
		return self.name + ' - ' + self.category

portfolio/forms.py
from django import forms
from .models import Portfolio


class PortfolioForm(forms.ModelForm):
	name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Project name'}))
	creator = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Project author'})) 
	description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Description'}))
	technologies = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Used technologies'})) 
	screen_link = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Preview image URL'})) 
	source_code_link = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'GitHub link'})) 
	project_link = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Project link'})) 


	class Meta:
		model = Portfolio
		fields = (
			'name', 
			'creator', 
			'category', 
			'description', 
			'technologies', 
			'screen_link', 
			'source_code_link', 
			'project_link')

portfolio/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Portfolio
from .forms import PortfolioForm
from django.contrib.auth.decorators import login_required


def portfolio_list(request):
	portfolio_list = Portfolio.objects.all()
	is_active = 'all_projects'
	return render(request, 'portfolio/portfolio_list.html', {
		'portfolio_list':portfolio_list,
		'is_active':is_active
		})


def portfolio_details(request, pk):
	portfolio_item = get_object_or_404(Portfolio, pk=pk)
	return render(request, 'portfolio/portfolio_detail.html', {'portfolio_item':portfolio_item})	


def portfolio_web(request):
	portfolio_list = Portfolio.objects.filter(category='Web')
	is_active = 'web'
	return render(request, 'portfolio/portfolio_list.html', {
		'portfolio_list':portfolio_list,
		'is_active':is_active
		})


def portfolio_programs(request):
	portfolio_list = Portfolio.objects.filter(category='Program')
	is_active = 'programs'
	return render(request, 'portfolio/portfolio_list.html', {
		'portfolio_list':portfolio_list,
		'is_active':is_active
		})


def portfolio_bots(request):
	portfolio_list = Portfolio.objects.filter(category='Bots')
	is_active = 'bots'
	return render(request, 'portfolio/portfolio_list.html', {
		'portfolio_list':portfolio_list,
		'is_active':is_active
		})


def portfolio_mobile_apps(request):
	portfolio_list = Portfolio.objects.filter(category='Mobile App')
	is_active = 'mobile_apps'
	return render(request, 'portfolio/portfolio_list.html', {
		'portfolio_list':portfolio_list,
		'is_active':is_active
		})


@login_required
def portfolio_add_project(request):
	if request.method == 'POST':
		form = PortfolioForm(request.POST)
		if form.is_valid():
			project = form.save(commit=False)
			project.save()
		return redirect('portfolio:portfolio_details', pk=project.pk)
	else:
		form = PortfolioForm()
	return render(request, 'portfolio/add_new_project.html', {'form':form})


@login_required
def portfolio_delete_project(request, pk):
	project = get_object_or_404(Portfolio, pk=pk)
	project.delete()
	return redirect('portfolio:portfolio_list')


@login_required
def portfolio_edit_project(request, pk):
	project = get_object_or_404(Portfolio, pk=pk)
	if request.method == 'POST':
		form = PortfolioForm(request.POST, instance=project)
		if form.is_valid():
			project = form.save(commit=False)
			project.save()
		return redirect('portfolio:portfolio_details', pk=project.pk)
	else:
		form = PortfolioForm(instance=project)
	return render(request, 'portfolio/edit_project.html', {'form':form})

portfolio/templates/portfolio/add_new_project.html
{% extends 'main/base.html' %}

{% block title %} Add new project {% endblock title%}


{% block content %}
	<form method="post">
	{% csrf_token %}
	<div class="container">
		<h1 class="portfolio-add-project-title">Add a new project to Portfolio</h1>
		<div class="row">
			<div class="col-md-12 portfolio-add-fields">

					{% for field in form %}
						<p>{{ field }}</p>
					{% endfor %}
					<button type="submit" class="btn btn-success add-project">Add new project</button>
			</div>
		</div>
	</div>
	</form>
{% endblock content %}

{% block footer %}
{% endblock footer %}

portfolio/templates/portfolio/edit_project.html
{% extends 'main/base.html' %}

{% block title %} Edit project {% endblock title%}


{% block content %}
	<form method="post">
	{% csrf_token %}
	<div class="container">
		<h1 class="portfolio-add-project-title">Edit project: </h1>
		<div class="row">
			<div class="col-md-12 portfolio-add-fields">

					{% for field in form %}
						<p>{{ field }}</p>
					{% endfor %}
					<button type="submit" class="btn btn-success add-project">Save</button>
			</div>
		</div>
	</div>
	</form>
{% endblock content %}

{% block footer %}
{% endblock footer %}

portfolio/templates/portfolio/portfolio_detail.html
{% extends 'main/base.html' %}

{% block title %} {{ portfolio_item.name }} {% endblock title%}


{% block content %}
	
	<div class="portfolio-detail-header">
		<h1> {{ portfolio_item.name }} </h1>
		<p>DETAILS OF THE PROJECT</p>
	</div>

	{% if user.is_authenticated %}
          <div class="portfolio-detail-admin-tools">
            <a class="btn btn-warning" href="{% url 'portfolio:portfolio_edit_project' pk=portfolio_item.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            <a class="btn btn-danger" href="{% url 'portfolio:portfolio_delete_project' pk=portfolio_item.pk %}" onclick="return confirm('Are you sure you want to delete this project?');"><span class="glyphicon glyphicon-remove"></span></a>
          </div>
    {% endif %}

	<hr>

	<div class="portfolio-detail-wrapper">
		<div class="container">
			<div class="row">
				<div class="col-md-5">
					<h3>PROJECT DESCRIPTION</h3>
					<p class="portfolio-detail-description"> {{ portfolio_item.description }} </p>

					<hr>

					<h5>PROJECT DETAILS:</h5>
					<div class="portfolio-detail-project-details">
						<p><strong>Author:</strong> {{ portfolio_item.creator }}</p>
						<p><strong>Catrgory:</strong> {{ portfolio_item.category }}</p>
						<p><strong>Technologies:</strong> {{ portfolio_item.technologies }}</p>
						<p><strong>Project link:</strong> <a href="{{ portfolio_item.project_link }}"> &nbsp; {{ portfolio_item.name }}</a></p>
						<p><strong>Source code:</strong> &nbsp; <a href="{{ portfolio_item.source_code_link }}"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a></p>
						<p><strong>Year:</strong> {{ portfolio_item.date.year }}</p>
						<hr>
						<a class="btn btn-default portfolio-contact-author" href="{% url 'contact:contact' %}">Contact the author</a>
					</div>
				</div>
			
				<div class="col-md-7">
					<img src="{{ portfolio_item.screen_link }}" width="100%" height="400px" class="img-responsive img-rounded">
				</div>
			</div>
		</div>
	</div>

{% endblock content %}

portfolio/templates/portfolio/portfolio_list.html
{% extends 'main/base.html' %}

{% block title %} Portflolio {% endblock title%}


{% block content %}
	<div class="portfolio-header">
		<h1> PORTFOLIO </h1>
		<p>MY FINISHED PROJECTS</p>
	</div>

	<hr>

	<div class="portfolio-list-wrapper">
		<div class="container-fluid">

			<div class="portfolio-navigation">
				<div class="row">
					<div class="col-md-12">
						<a href="{% url 'portfolio:portfolio_list' %}" class="btn btn-default portfolio-navigation-button 
						{% if is_active == 'all_projects' %} active {% endif %}"> ALL PROJECTS </a>
						<a href="{% url 'portfolio:portfolio_web' %}" class="btn btn-default portfolio-navigation-button {% if is_active == 'web' %} active {% endif %}"> WEB </a>
						<a href="{% url 'portfolio:portfolio_programs' %}" class="btn btn-default portfolio-navigation-button {% if is_active == 'programs' %} active {% endif %}"> PROGRAMS </a>
						<a href="{% url 'portfolio:portfolio_bots' %}" class="btn btn-default portfolio-navigation-button {% if is_active == 'bots' %} active {% endif %}"> BOTS </a>
						<a href="{% url 'portfolio:portfolio_mobile_apps' %}" class="btn btn-default portfolio-navigation-button {% if is_active == 'mobile_apps' %} active {% endif %}"> MOBILE APPS </a>
					</div>
				</div>
			</div>

			<div class="row">
				{% for item in portfolio_list %}
					<div class="col-md-4 portfolio-list">
						<a href="{% url 'portfolio:portfolio_details' pk=item.pk %}">
							<img src="{{ item.screen_link }}" class="img-responsive" width="100%" height="300">
						</a>
						<div class="portfolio-list-description">
							<span> <a href="{% url 'portfolio:portfolio_details' pk=item.pk %}">Click for detail</a> </span>
							<p><strong>Name: </strong>{{ item.name }}</p>
							<p><strong>Category: </strong>{{ item.category }}</p>
						</div>
					</div>
				{% empty %}
					<p>Portfolio list is empty</p>
				{% endfor%}
			</div>
			<hr>
		</div>
	</div>


{% endblock content %}