blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'

urlpatterns = [

	#list of posts
	url(r'^$', views.post_list, name ='post_list'),

	#details of post + comments
	url(r'^post/(?P<pk>\d+)/$', views.post_detail, name ='post_detail'),

	#adding post
	url(r'^post/new/$', views.post_add, name='post_add'),

	#publishing post
	url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),

	#draft posts
	url(r'^draft_posts$', views.post_drafts, name='post_drafts'),

	#editing post
	url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),

	#removing post
	url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),

	#removing comment
	url(r'^post/(?P<pk>\d+)/comment_remove/$', views.comment_remove, name='comment_remove'),

]

cvsite/urls.py
from django.conf.urls import include, url 
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^accounts/login/$', login, {'template_name': 'main/admin/login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinLengthValidator


class Post(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=100)
	text = models.TextField()
	text_preview = models.TextField(max_length=200, validators=[MinLengthValidator(100)])
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)


	def publish(self):
		self.published_date = timezone.now
		self.save()


	def __str__(self):
		return self.title


class Comment(models.Model):
	post = models.ForeignKey(Post)
	author = models.CharField(max_length=30)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)


	def __str__(self):
		return self.text

blog/forms.py
from django import forms
from .models import Comment, Post


class PostForm(forms.ModelForm):

	class Meta:
	    model = Post
	    fields = ('title', 'text', 'text_preview')



class CommentForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super(CommentForm, self).__init__(*args, **kwargs)
		for field_name in self.fields:
			field = self.fields.get(field_name)  
			if field:
				if type(field.widget) is (forms.Textarea):
					field.widget = forms.Textarea(attrs={'placeholder': 'Your comment ...', 'class': 'form-control'})
				elif type(field.widget) is (forms.TextInput):
					field.widget = forms.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'})



	class Meta:
	    model = Comment
	    fields = ('author', 'text')
	    

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post, Comment
from .forms import CommentForm, PostForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required


def post_list(request):
	post_list = Post.objects.all().order_by('-published_date')
	paginator = Paginator(post_list, 6)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1) # Calls page with index 1, if page not found calls except InvalidPage
	except EmptyPage:
		posts = paginator.page(paginator.num_pages) 		# Get number of all pages 
	return render(request, 'blog/post_list.html', {'posts':posts})


def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = CommentForm()
	comments = post.comment_set.filter(created_date__lte=timezone.now()).order_by('-created_date')
	return render(request, 'blog/post_detail.html', {
		'form': form, 
		'post':post,
		'comments':comments,
		})


@login_required
def post_drafts(request):
	posts = Post.objects.filter(published_date__isnull=True).order_by('-created_date')
	return render(request, 'blog/post_drafts.html', {'posts':posts})


@login_required
def post_add(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit = False)
			post.author = request.user
			post.save()
		return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm()
	return render(request, 'blog/post_add.html', {'form':form})


@login_required
def post_publish(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.published_date = timezone.now()
	post.save()
	return redirect('blog:post_detail', pk=pk)


@login_required
def post_edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		form = PostForm(request.POST, instance = post)
		if form.is_valid():
			post = form.save(commit = False)
			post.author = request.user
			post.save()
		return redirect('blog:post_detail', pk = post.pk)
	else:
		form = PostForm(instance = post)
	return render(request, 'blog/post_edit.html', {'form':form})


@login_required
def post_remove(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.delete()
	return redirect('blog:post_list')


@login_required
def comment_remove(request, pk):
	comment = get_object_or_404(Comment, pk=pk)
	comment.delete()
	return redirect('blog:post_detail', pk=comment.post.pk)

blog/templates/blog/post_add.html
{% extends 'main/base.html' %}

{% block title %} Add a new post {% endblock %}

{% block content %}

<form method="post" class="post-form">
	{% csrf_token %}
	<div class="container">
		<h1 class="post-add-title">Add a new blog post</h1>
		<div class="row">
			<div class="col-md-6">
				{% for field in form %}
					<p>{{ field.label_tag }}</p>
					<p>{{ field }}</p>
				{% endfor %}
			
				<button type="submit" class="btn btn-success add-post">Add post to draft list</button>
			</div>
		</div>
	</div>
</form>


{% endblock content %}

{% block footer %}
{% endblock footer %}

blog/templates/blog/post_detail.html
{% extends 'main/base.html' %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="post-detail-title">{{ post.title }}</h1>

        {% if post.published_date %}
          <p class="post-detail-date">{{ post.published_date }}</p>
        {% endif %}

        {% if user.is_authenticated %}
          <div class="post-detail-admin-tools">
            <a class="btn btn-warning" href="{% url 'blog:post_edit' post.pk%}"><span class="glyphicon glyphicon-pencil"></span></a>
            <a class="btn btn-danger" href="{% url 'blog:post_remove' post.pk%}" onclick="return confirm('Are you sure you want to delete this post?');"><span class="glyphicon glyphicon-remove"></span></a>
            {% if not post.published_date %}
                <a class="btn btn-success" href="{% url 'blog:post_publish' post.pk %}">Publish</a>
            {% endif %}
          </div>
        {% endif %}

        <div class="post-detail-text">
          <p>{{ post.text|linebreaksbr }}</p>
          <hr>
        </div>
        
      </div>
    </div>

    <div class="row">
      <div class="col-md-7" id="comment-wrapper">
      	<h4>Comments:</h4>
      	{% for comment in comments %}
          	<div class="comment">
                <div class="post-detail-admin-tools">
                  {% if user.is_authenticated %}
                    <a class="btn btn-danger btn-xs" href="{% url 'blog:comment_remove' pk=comment.pk %}" onclick="return confirm('Are you sure you want to delete this comment?');"><span class="glyphicon glyphicon-remove"></span></a>
                  {% endif %}
                </div>
            		<strong class="comment-author">{{ comment.author }}</strong>
                <div class="comment-date">
                    {{ comment.created_date }}
                </div>
             		<p>{{ comment.text|linebreaks }}</p>           
         		</div>
         	{% empty %}
            <div class="empty-comments"> 
            	<p>No comments here yet :(</p>
            	<p>You can be first! Just press "Leave comment" button :)</p>
            </div>
      	{% endfor %}
      </div> 
      <div class="col-md-5"> 

    	  <form action="{% url 'blog:post_detail' post.pk %}" method="post" class="post-form comment-form">
          {% csrf_token %}
          <h4>Leave comment:</h4>
              <div class="comment-form-fields">
                {% for field in form %}
                  <div class="fieldWrapper">
                    <p>{{ field }}</p>               
                  </div>
                {% endfor %}
              </div>
          <button type="submit" class="btn btn-primary send-comment">Leave comment</button>
        </form>

      </div>
    </div>
  </div> 
{% endblock content %}

blog/templates/blog/post_drafts.html
{% extends 'main/base.html' %}

{% block title %} Draft posts {% endblock %}

{% block content %}


<div class="container">
	<div class="row">
		<div class="col-md-12 post-draft-list">
			<h1>LIST OF DRAFT POSTS:</h1>
			{% for post in posts %}
				<a href="{% url 'blog:post_detail' post.pk %}" class="post-draft-list-title">{{ post.title }}</a>
				<p>{{ post.text_preview | linebreaksbr }}</p>
				<p class="post-draft-list-created-date">Created date:&nbsp;&nbsp;&nbsp;{{ post.created_date }}</p>
				<br>
				<hr>
			{% empty %}
				<p class="post-draft-list-empty">Draft list is empty.</p>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock content %}

{% block footer %}
{% endblock footer %}

blog/templates/blog/post_edit.html
{% extends 'main/base.html' %}

{% block title %} Edit post {% endblock %}

{% block content %}

<form method="post" class="post-form">
	{% csrf_token %}
	<div class="container">
		<h1 class="post-add-title">Post edit</h1>
		<div class="row">
			<div class="col-md-6">
				{% for field in form %}
					<p>{{ field.label_tag }}</p>
					<p>{{ field }}</p>
				{% endfor %}
			
				<button type="submit" class="btn btn-success add-post">Save</button>
			</div>
		</div>
	</div>
</form>



{% endblock content %}


{% block footer %}
{% endblock footer %}

blog/templates/blog/post_list.html
{% extends 'main/base.html' %}

{% block title %} Blog {% endblock %}

{% block content %}

    <h1 class='blog-title'>BLOG</h1>

    <hr>

	
    <div class="container-fluid">
       <div class="row post-list-container">
            {% for post in posts %} 
                <div class="col-xs-6 col-md-3 post-list">
                    <a href="{% url 'blog:post_detail' pk=post.pk %}" class="post-list-link">    
                        <h1 class="post-list-title">{{ post.title }}</h1>
                        <p class="post-list-date">{{ post.published_date }}</p>
                        <p class="post-list-text">{{ post.text_preview|linebreaksbr }}</p>
                        <p class="post-list-comments">Comments: {{ post.comment_set.all.count }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>  

        <div id="pages">
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}<br>
            </span>
            {% if posts.has_previous %}
                <a href="?page={{ posts.previous_page_number }}" class="btn btn-default btn-xs" role="button" id="page_button">Previous page</a>
                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}" class="btn btn-default btn-xs" role="button" id="page_button">Next page</a>
                {% else %}
                    <a href="/" class="btn btn-default btn-xs disabled" role="button" id="page_button">Next page</a>
                {% endif %}
            {% elif posts.has_next %}
                <a href="/" class="btn btn-default btn-xs disabled" role="button" id="page_button">Previous page</a>
                <a href="?page={{ posts.next_page_number }}" class="btn btn-default btn-xs" role="button" id="page_button">Next page</a>
            {% endif %}
        </div>
        
    </div>
    

{% endblock content %}