blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'

urlpatterns = [

	#list of posts
	url(r'^$', views.post_list, name ='post_list'),

	#details of post + comments
	url(r'^post/(?P<pk>\d+)/$', views.post_detail, name ='post_detail'),

	#adding post
	url(r'^post/new/$', views.post_add, name='post_add'),

	#publishing post
	url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),

	#draft posts
	url(r'^draft_posts$', views.post_drafts, name='post_drafts'),

	#editing post
	url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),

	#removing post
	url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),

	#removing comment
	url(r'^post/(?P<pk>\d+)/comment_remove/$', views.comment_remove, name='comment_remove'),

]

contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns = [
	url(r'^$', views.contact , name = "contact" ),
	url(r'^messages/$', views.message_list , name = "message_list" ),
	url(r'^messages/(?P<pk>\d+)/$', views.message_detail , name = "message_detail" ),
	url(r'^messages/delete/(?P<pk>\d+)/$', views.message_delete , name = "message_delete" ),
]

cvsite/urls.py
from django.conf.urls import include, url 
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^accounts/login/$', login, {'template_name': 'main/admin/login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
]

main/urls.py
from django.conf.urls import url
from . import views


app_name = 'main'

urlpatterns = [
	url(r'^$', views.home , name = "home" ),
	url(r'^about_me/$', views.about_me , name = "about_me" ),
]

portfolio/urls.py
from django.conf.urls import url 
from . import views

app_name = 'portfolio'

urlpatterns = [
    url(r'^$', views.portfolio_list, name='portfolio_list'),
    url(r'^details/(?P<pk>\d+)/$', views.portfolio_details, name='portfolio_details'),
    url(r'^web/$', views.portfolio_web, name='portfolio_web'),
    url(r'^program/$', views.portfolio_programs, name='portfolio_programs'),
    url(r'^bots/$', views.portfolio_bots, name='portfolio_bots'),
    url(r'^mobile_apps/$', views.portfolio_mobile_apps, name='portfolio_mobile_apps'),
    url(r'^add_project/$', views.portfolio_add_project, name='portfolio_add_project'),
    url(r'^delete/(?P<pk>\d+)/$', views.portfolio_delete_project, name='portfolio_delete_project'),
    url(r'^edit/(?P<pk>\d+)/$', views.portfolio_edit_project, name='portfolio_edit_project')
]

main/forms.py
from django import forms

main/views.py
from django.shortcuts import render, redirect
from contact.models import Contact


def home(request):
	messages = Contact.objects.all()
	return render(request, 'main/home.html', {'messages':messages})


def about_me(request):
	return render(request, 'main/about_me.html')

main/templates/main/about_me.html
{% extends 'main/base.html' %}

{% block title %} About me {% endblock title %}



{% block content %} 


	<div class="about-me-header">
		<h1> ABOUT ME </h1>
		<p> I AM ALEXANDR NIKITENKO </p>
	</div>

	<hr>

	<div class="container-fluid about-me-wrapper">
		<div class="row">
			<div class="col-md-4">
				<img src="../static/main/img/my_photo.jpg" class="img-rounded img-responsive" alt="my photo">
			</div>
			<div class="col-md-4 about-me-info">
				<p><strong>Full name:</strong> Alexandr Nikitenko</p>
				<p><strong>Address:</strong> Kiev, Ukraine</p>
				<p><strong>Phone:</strong> +3806334****7</p>
				<p><strong>Email:</strong> <a href="{% url 'contact:contact' %}">sashanikitenko74@gmail.com</a></p>
			</div>
			<div class="col-md-4 about-me-info">
				<p><strong>Date of Bithday:</strong> 14 March 1997</p>
				<p><strong>Job:</strong> None</p>
				<p><strong>Skype:</strong> alex_nikitenko97</p>
				<p><strong>WebSite:</strong> <a href="">www.a_nikitenko_cv.com</a></p>
			</div>

			<div class="col-md-8 about-me-text">
				<hr>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec sem nisi. Donec sollicitudin metus eget libero finibus semper. Pellentesque at efficitur tortor, non iaculis felis. Quisque vel mi finibus, cursus sapien ac, sodales purus. Mauris eu congue nisi. Maecenas ut consectetur diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque fringilla facilisis nulla at fermentum. Vestibulum vitae semper sapien. Duis commodo risus in sapien pretium, at mollis orci ultrices. Aliquam vitae aliquet lectus. Proin iaculis odio quis lorem volutpat, vitae convallis velit vehicula. Aliquam at nulla at odio euismod blandit.</p>

			</div>
			<div class="col-md-2 about-me-buttons">
				<a href="{% url 'contact:contact' %}"><button class="btn btn-default">HIRE ME</button></a>
			</div>
			<div class="col-md-2 about-me-buttons">
				<a href="#"><button class="btn btn-default">DOWNLOAD RESUME</button></a>
			</div>
		</div>
	</div>

	<div class="my-skills-wrapper">
		<div class="my-skills-header">
			<h1> MY SKILLS </h1>
			<p> MY OWN ESTIMATE* </p>
		</div>

		<div class="container">
			<p id="asterisk-text">* How I can assess my knowledge</p>
			<hr>
		</div>

		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="my-skills-scales-wrapper">
					 	<div class="col-md-6">
					 		
					 		<p class="scale-top-text">HTML / CSS - 70%</p>
					 		<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
								    <span class="sr-only">70% Complete</span>
								</div>
							</div>

							<p class="scale-top-text">JS / jQuery - 20%</p>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%;">
								    <span class="sr-only">20% Complete</span>
								</div>
							</div>

							<p class="scale-top-text">ReactJS / AngularJS - 0%</p>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
								    <span class="sr-only">0% Complete</span>
								</div>
							</div>

							<p class="scale-top-text">AJAX - 0%</p>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
								    <span class="sr-only">0% Complete</span>
								</div>
							</div>

					 	</div>
					 	<div class="col-md-6">
					 		
					 		<p class="scale-top-text">Python3 / Python2 (Standard Library) - 85%</p>
					 		<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%;">
								    <span class="sr-only">85% Complete</span>
								</div>
							</div>

							<p class="scale-top-text">Django Framework - 67%</p>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="67" aria-valuemin="0" aria-valuemax="100" style="width: 67%;">
								    <span class="sr-only">67% Complete</span>
								</div>
							</div>

							<p class="scale-top-text">SQL (MySQL, PostgreSQL, SQLite) - 30%</p>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%;">
								    <span class="sr-only">30% Complete</span>
								</div>
							</div>

							<p class="scale-top-text">NoSQL(MongoDB, ElacticSearch, Redis) - 0%</p>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
								    <span class="sr-only">0% Complete</span>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

{% endblock content %}

main/templates/main/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
    	<title>{% block title %} My CV {% endblock %}</title>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Bootstrap -->
    	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    	
    	<!-- CSS -->
    	<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    	<link rel="stylesheet" href="{% static 'main/css/about_me.css' %}">
    	<link rel="stylesheet" href="{% static 'contact/css/contact.css' %}">
    	<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
    	<link rel="stylesheet" href="{% static 'portfolio/css/portfolio.css' %}">

		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

		<!-- Font Awesome icons -->
		<script src="https://use.fontawesome.com/eacec2fe3f.js"></script>

	</head>
	<body>
		{% if user.is_authenticated %}
			<nav class="navbar navbar-inverse navbar-wrapper">
			  <div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#all-navigation" aria-expanded="false">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="{% url 'main:home' %}">ADMIN-PANEL</a>
			    </div>

			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="all-navigation">
			      <ul class="nav navbar-nav">
			        <li><a href="{% url 'blog:post_add' %}">Blog: Add new post </a></li>
			        <li><a href="{% url 'blog:post_drafts' %}">Blog: Post Draft list {% if draft_posts.count %} <span class="badge">{{ draft_posts.count }} new</span>{% endif %}</a></li>
			        <li><a href="{% url 'portfolio:portfolio_add_project' %}">Portfolio: Add new project </a></li>
			      </ul>
			      
			      <ul class="nav navbar-nav navbar-right">
			      	<li><a href="{% url 'contact:message_list' %}">Messages {% if new_messages.count %} <span class="badge">{{ new_messages.count }} new</span>{% endif %}</a></li>
			      	<li><a>Signed in as ' {{ user.username }} '</a></li>
			        <li><a href="{% url 'logout' %}?next={{ request.path }}" title='logout'><span class="glyphicon glyphicon-off logout"></span></a></li>
			      </ul>
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>
		{% endif %}

		<div id="wrapper">
		<!-- SideBar -->

			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<li id="menu-toggle"><a href="#"><span class="glyphicon glyphicon-menu-hamburger"></span></a></li>
					<li>
						<a href="{% url 'main:home' %}"> 
						<span class="glyphicon glyphicon-home sidebar-logos"></span>
						<p class="sidebar-items">HOME</p>
						</a>
					</li>
					<li>
						<a href="{% url 'main:about_me' %}"> 
						<span class="glyphicon glyphicon-user sidebar-logos"></span>
						<p class="sidebar-items">ABOUT ME</p>
						</a>
					</li>
					<li>
						<a href="{% url 'portfolio:portfolio_list' %}"> 
						<span class="glyphicon glyphicon-folder-close sidebar-logos"></span>
						<p class="sidebar-items">PORTFOLIO</p>
						</a>
					</li>
					<li>
						<a href="{% url 'blog:post_list' %}"> 
						<span class="glyphicon glyphicon-book sidebar-logos"></span>
						<p class="sidebar-items">BLOG</p>
						</a>
					</li>
					<li>
						<a href="{% url 'contact:contact' %}"> 
						<span class="glyphicon glyphicon-send sidebar-logos"></span>
						<p class="sidebar-items">CONTACT</p>
						</a>
					</li>
					<li>
						{% if not user.is_authenticated %}
							<a href="{% url 'login' %}?next={{ request.path }}" title="login"><span class="glyphicon glyphicon-lock"></span></a>
						{% endif %}
					</li>
				</ul>
			</div>

		<!-- SideBar END-->

		<!-- Page Content -->
			
			<div id="page-content-wrapper">
				<div class="content container-fluid">
					<div class="row">
						<div class="col-lg-12 content">

							{% block content %}

                    		{% endblock content %}

						</div>
					</div>
				</div>
			</div>
		<!-- Page Content END -->
		</div>
		{% block footer %}
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-12 footer">
						<p>Made by Alexandr Nikitenko</p>
						<p>2017 All rights reserved &reg;</p>
					</div>
				</div>
			</div>
		{% endblock footer %}




		<!-- JQuery -->
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
		<!-- Bootstrap -->
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
		<!-- JS -->
		<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>
		<script type="text/javascript" src="{% static 'blog/js/blog.js' %}"></script>
		<script type="text/javascript" src="{% static 'portfolio/js/portfolio.js' %}"></script>
		<script type="text/javascript" src="{% static 'contact/js/contact.js' %}"></script>
	</body>
</html>

main/templates/main/home.html
{% extends 'main/base.html' %}

{% block content %}
	<div class="home-wrapper">
		<div class="home-header">
			<span class="glyphicon glyphicon-arrow-left" id="start-arrow"></span>
			<p> GET STARTED </p>
		</div>

		<div class="container-fluid">
			<div class="row home-first-row">
				<div class="col-md-6 col-md-offset-3">
					<div class="panel panel-default" id='panel'>
					  	<div class="panel-body home-hello">
					    	<span class="after">HELLO!</span>
					 	 </div>
					</div>
				</div>
			</div>
			<div class="row home-second-row">
				<div class="col-md-12">
					<div class="panel panel-default" id='panel'>
					  	<div class="panel-body home-text">
					    	<span>&nbsp;&nbsp;&nbsp;I'M ALEX NIKITENKO...</span>
					 	 </div>
					</div>
				</div>
			</div>
		</div>

	</div>


{% endblock content %}


{% block footer %}

{% endblock footer %}