blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'

urlpatterns = [

	#list of posts
	url(r'^$', views.post_list, name ='post_list'),

	#details of post + comments
	url(r'^post/(?P<pk>\d+)/$', views.post_detail, name ='post_detail'),

	#adding post
	url(r'^post/new/$', views.post_add, name='post_add'),

	#publishing post
	url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),

	#draft posts
	url(r'^draft_posts$', views.post_drafts, name='post_drafts'),

	#editing post
	url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),

	#removing post
	url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),

	#removing comment
	url(r'^post/(?P<pk>\d+)/comment_remove/$', views.comment_remove, name='comment_remove'),

]

contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns = [
	url(r'^$', views.contact , name = "contact" ),
	url(r'^messages/$', views.message_list , name = "message_list" ),
	url(r'^messages/(?P<pk>\d+)/$', views.message_detail , name = "message_detail" ),
	url(r'^messages/delete/(?P<pk>\d+)/$', views.message_delete , name = "message_delete" ),
]

cvsite/urls.py
from django.conf.urls import include, url 
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^accounts/login/$', login, {'template_name': 'main/admin/login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
]

contact/models.py
from django.db import models
from django.utils import timezone


class Contact(models.Model):
	name = models.CharField(max_length=100)
	subject = models.CharField(max_length=100)
	email = models.CharField(max_length=150)
	text = models.TextField()
	send_date = models.DateTimeField(default = timezone.now)
	is_read = models.BooleanField(default=False)


	def email_read(self):
		self.is_read = True
		self.save()
	

	def __str__(self):
		return self.email + " - Re: " +self.subject

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
	name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your name'}))
	subject = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Subject'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Your email'}))
	text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Your message ...'}))
	
	class Meta:
	    model = Contact
	    fields = ('name', 'subject', 'email', 'text')

contact/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ContactForm
from .models import Contact
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
        	form.save()
        	return redirect('contact:contact')
    else:
        form = ContactForm()
    return render(request, 'contact/contact.html', {'form': form})


@login_required
def message_list(request):
	message_list = Contact.objects.all().order_by('-send_date')
	paginator = Paginator(message_list, 10)
	page = request.GET.get('page')
	try:
		messages = paginator.page(page)
	except PageNotAnInteger:
		messages = paginator.page(1) # Calls page with index 1, if page not found calls except InvalidPage
	except EmptyPage:
		messages = paginator.page(paginator.num_pages)
	return render(request, 'contact/message_list.html', {'messages':messages})
  

@login_required
def message_detail(request, pk):
	message = get_object_or_404(Contact, pk=pk)
	message.email_read()
	return render(request, 'contact/message_detail.html', {'message': message})


@login_required
def message_delete(request, pk):
	message = get_object_or_404(Contact, pk=pk)
	message.delete()
	return redirect('contact:message_list')
  

contact/templates/contact/contact.html
{% extends 'main/base.html' %}

{% block title %} Contact {% endblock %}
	
{% block content %}

	<div class="contact-header">
		<h1> LET'S TALK</h1>
		<p>GET IN TOUCH WITH ME</p>
	</div>

	<hr>

	<div class="container-fluid">
		<p class="contacts-alert">Please Feel free to get in Touch Anytime, whenever for Work Inquiries of just to say Hello!</p>

		<div class="row">
			<div class="col-md-6">
				<div class="contact-form-wrapper">

					<form action="{% url 'contact:contact' %}" method="post">
   						{% csrf_token %}
   						<div class="form-group">	
	   						<p class="contact-field-name-email">{{ form.name }} &nbsp; {{ form.email }}</p>
	   						<p class="contact-field-subject">{{ form.subject }}</p>
	   						<p class="contact-field-text">{{ form.text }}</p>
   						</div>
						<input type="submit" class="btn btn-default send-message" value="SEND MESSAGE" id="send-message">
					</form>

				</div>
			</div>

			<div class="col-md-4">
				<div class="contact-info-wrapper">

					<div class="address">
						<h4>ADDRESS</h4>
						<p>Ukraine, Kiev</p>
						<p>Solomianska str.</p>
						<hr>
					</div>

					<div class="contact-info">
						<h4>CONTACT INFO</h4>
						<p>sashanikitenko74@gmail.com</p>
						<p>+3806334****7</p>
						<hr>
					</div>

					<div class="social-networks">
						<h4>SOCIAL NETWORKS</h4>
						<a href="https://www.facebook.com/sashka47"><i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i></a>
						<a href="http://vk.com/id65443143"><i class="fa fa-vk fa-2x" aria-hidden="true"></i></a>
						<a title="@Ghost_74"><i class="fa fa-telegram fa-2x" aria-hidden="true"></i></a>
						<hr>
					</div>


				</div>
			</div>

		</div>
	</div>



{% endblock content%}

contact/templates/contact/message_detail.html
{% extends 'main/base.html' %}

{% block title %} {{ message.subject }} {% endblock %}
	
{% block content %}

	<div class="container message-detail-wrapper">
		<div class="row">
			<div class="col-md-12">
				<div class="well well-lg message-cover">	
				<a class="btn btn-danger" href="{% url 'contact:message_delete' message.pk%}" onclick="return confirm('Are you sure you want to delete this message?');"><span class="glyphicon glyphicon-remove"></span></a>
					<p class='message-author'>Message by <strong>{{ message.name }}</strong></p>

					<div class="panel panel-default">
					  	<div class="panel-body">
					    	<strong>Email: </strong>{{ message.email }}
					  	</div>
					</div>

					<div class="panel panel-default">
					  	<div class="panel-body">
					    	<strong>Subject: </strong>{{ message.subject }}
					  	</div>
					</div>

					<div class="panel panel-default">
					  	<div class="panel-body">
					    	<strong>Message: </strong> <br><br> {{ message.text }}
					  	</div>
					</div>

					<p class='message-send-date'>Sent: {{ message.send_date }}</p>
				
				</div>
			</div>
		</div>
	</div>

{% endblock content %}



{% block footer %}
{% endblock footer %}

contact/templates/contact/message_list.html
{% extends 'main/base.html' %}

{% block title %} Messages {% if new_messages %}({{ new_messages.count }} new) {% endif %}{% endblock %}
	
{% block content %}
	
	<div class="container message-main-wrapper">
		<div class="row">
			<h1 class="messages-title"> PRIVATE MESSAGES </h1>
			{% if messages %}
				<div id="pages">
				   	<span id="current-page">Page {{ messages.number }} of {{ messages.paginator.num_pages }}</span>
				    {% if messages.has_previous %}
				        <a href="?page={{ messages.previous_page_number }}" class="btn btn-default btn-xs" role="button"><span class="glyphicon glyphicon-menu-left"></span></a>
				        {% if messages.has_next %}
				            <a href="?page={{ messages.next_page_number }}" class="btn btn-default btn-xs" role="button"><span class="glyphicon glyphicon-menu-right"></span></a>
				        {% else %}
					        <a href="/" class="btn btn-default btn-xs disabled" role="button"><span class="glyphicon glyphicon-menu-right"></span></a>
				        {% endif %}
			        {% elif messages.has_next %}
			            <a href="/" class="btn btn-default btn-xs disabled" role="button"><span class="glyphicon glyphicon-menu-left"></span></a>
			            <a href="?page={{ messages.next_page_number }}" class="btn btn-default btn-xs" role="button"><span class="glyphicon glyphicon-menu-right"></span></a>
			        {% endif %}
			    </div>			
			{% endif %}
			<div class="col-md-12 messages-list-wrapper">

				{% for message in messages %}
					<a href="{% url 'contact:message_detail' pk=message.pk %}" class="single-message">
					{% if not message.is_read %}<strong>{% endif %}
						<div class="row">
							<div class="col-md-2">
								<p>{{ message.name }}</p>
							</div>
							<div class="col-md-3">
								<p>{{ message.email }}</p>
							</div>
							<div class="col-md-5">
								<p>Re: {{ message.subject }}</p>
							</div>
							<div class="col-md-2">
								<p>{{ message.send_date }}</p>
							</div>
						</div>
					{% if not message.is_read %}</strong>{% endif %}
					</a>
				{% empty %}
					<p class="empty-messages"> No any message </p>
				{% endfor %}

			</div>
		</div>
	</div>

{% endblock content%}


{% block footer %}
{% endblock footer %}